leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 1500
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 16
iqtree_seed: 2211919003
pygargammel_seed: 1211154244
query_selection_seed: 1956961036
