name: conda_venv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - iqtree=3.0.1
  - numpy=2.0.2
  - scipy=1.13.1
  - matplotlib=3.9.4
  - pillow=11.2.1
  - h5py=3.14.0
  - biopython=1.85
  - psutil=7.0.0
  - tornado=6.5.1
  - pyyaml=6.0.2
  - jinja2=3.1.6
  - fonttools=4.58.0
  - kiwisolver=1.4.7
  - python-dateutil=2.9.0.post0
  - six=1.17.0
  - cycler=0.12.1
  - contourpy=1.3.0
  - pluggy=1.6.0
  - pytest=8.3.5
  - pip
  - pip:
      - annotated-types==0.7.0
      - cloudpickle==3.1.1
      - exceptiongroup==1.3.0
      - gprof2dot==2025.4.14
      - importlib_resources==6.5.2
      - iniconfig==2.1.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - maturin==1.8.4
      - pydantic==2.11.7
      - pydantic_core==2.33.2
      - Pygments==2.19.2
      - pyparsing==3.2.3
      - rich==14.0.0
      - scalene==1.5.51
      - snakeviz==2.2.2
      - tomli==2.2.1
      - typing-inspection==0.4.1
      - typing_extensions==4.13.2
      - zipp==3.21.0
