leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 3000305117
pygargammel_seed: 2247943603
query_selection_seed: 2054137934
mutation_rate: 0.04
mutation_seed: 2457753307
disorientation_probability: -1
disorientation_seed: -1
