leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 3288321499
pygargammel_seed: 3200285044
query_selection_seed: 1317546066
mutation_rate: 0.09
mutation_seed: 4150870805
disorientation_probability: 0.5
disorientation_seed: 889789698
