leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 2204063047
pygargammel_seed: 1897101390
query_selection_seed: 2924612700
mutation_rate: 0.08
mutation_seed: 2438938579
disorientation_probability: 0.5
disorientation_seed: 1173665233
