leaf_count: 800
sequence_length: 50000
tree_height: 1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 3837741995
pygargammel_seed: 408072379
query_selection_seed: 2027654161
mutation_rate: -1
mutation_seed: -1
disorientation_probability: -1
disorientation_seed: -1
