leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 3715550729
pygargammel_seed: 3548962998
query_selection_seed: 1733279107
mutation_rate: 0.04
mutation_seed: 3446385530
disorientation_probability: 0.5
disorientation_seed: 2493211885
