leaf_count: 1000
sequence_length: 50000
tree_height: 0.05
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 1692505523
pygargammel_seed: 1879740571
query_selection_seed: 4121044808
mutation_rate: -1
mutation_seed: -1
disorientation_probability: 0.5
disorientation_seed: 2872077029
