leaf_count: 1000
sequence_length: 50000
tree_height: 0.07
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 2026319391
pygargammel_seed: 3995251727
query_selection_seed: 3245859445
mutation_rate: -1
mutation_seed: -1
disorientation_probability: 0.5
disorientation_seed: 925972492
