leaf_count: 1000
sequence_length: 50000
tree_height: 0.03
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 1473900427
pygargammel_seed: 1015770
query_selection_seed: 3392047825
mutation_rate: -1
mutation_seed: -1
disorientation_probability: 0.5
disorientation_seed: 3523941705
