leaf_count: 1200
sequence_length: 50000
tree_height: 0.1
query_count: 800
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 389222251
pygargammel_seed: 2070163411
query_selection_seed: 1109091565
mutation_rate: -1
mutation_seed: -1
disorientation_probability: -1
disorientation_seed: -1
