leaf_count: 1000
sequence_length: 50000
tree_height: 0.13
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 1727710976
pygargammel_seed: 1789630417
query_selection_seed: 3175800649
mutation_rate: -1
mutation_seed: -1
disorientation_probability: -1
disorientation_seed: -1
