leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 3090614030
pygargammel_seed: 3625525556
query_selection_seed: 4137494748
mutation_rate: 0.02
mutation_seed: 1748752783
disorientation_probability: 0.5
disorientation_seed: 1415953944
