leaf_count: 2000
sequence_length: 50000
tree_height: 1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 1951103562
pygargammel_seed: 4229094583
query_selection_seed: 4265232022
mutation_rate: -1
mutation_seed: -1
disorientation_probability: -1
disorientation_seed: -1
