leaf_count: 1000
sequence_length: 50000
tree_height: 0.01
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 8
iqtree_seed: 2769059594
pygargammel_seed: 2331272007
query_selection_seed: 4238179911
mutation_rate: 0.08
mutation_seed: 2421935954
disorientation_probability: 0.5
disorientation_seed: 290101317
