leaf_count: 1000
sequence_length: 50000
tree_height: 0.1
query_count: 200
query_min_length: 100
fragment_count: 50
nick_freq: 0.005
overhang_parameter: 1.0
double_strand_deamination: 0.0
single_strand_deamination: 0.0
core_count: 24
iqtree_seed: 1434415971
pygargammel_seed: 1818985676
query_selection_seed: 2171777426
mutation_rate: -1
mutation_seed: -1
disorientation_probability: -1
disorientation_seed: -1
